import streamlit as st
import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
import numpy as np
from PIL import Image, ImageStat
from fpdf import FPDF
import tempfile
import time
import os

# ---------------------------------------------------------------------
# 1. Page Configuration
# ---------------------------------------------------------------------
st.set_page_config(
    page_title="LungsAI - Medical Diagnosis System",
    page_icon="🫁",
    layout="centered",
    initial_sidebar_state="expanded"
)

# Custom CSS
st.markdown("""
    <style>
    .main {
        background-color: #f8f9fa;
    }
    h1 {
        color: #0b5394;
        font-family: 'Arial', sans-serif;
    }
    .stButton>button {
        color: white;
        background-color: #0b5394;
        border: none;
        border-radius: 8px;
        padding: 10px 24px;
        font-weight: bold;
        width: 100%;
        transition: 0.3s;
    }
    .stButton>button:hover {
        background-color: #073763;
    }
    </style>
    """, unsafe_allow_html=True)

# ---------------------------------------------------------------------
# 2. HELPER FUNCTIONS
# ---------------------------------------------------------------------

# --- PDF Generation Logic ---
def create_pdf(patient_img, prediction_text, confidence, is_pneumonia):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    
    # Title
    pdf.cell(200, 10, txt="LungsAI - Medical Diagnosis Report", ln=True, align='C')
    pdf.ln(10)
    
    # Date & Time
    pdf.set_font("Arial", size=10)
    pdf.cell(200, 10, txt="Generated on: " + time.strftime("%Y-%m-%d %H:%M:%S"), ln=True, align='R')
    pdf.ln(10)
    
    # Diagnosis Result
    pdf.set_font("Arial", 'B', 14)
    if is_pneumonia:
        pdf.set_text_color(194, 24, 7) # Red
    else:
        pdf.set_text_color(0, 128, 0) # Green
        
    pdf.cell(200, 10, txt=f"Diagnosis: {prediction_text}", ln=True, align='L')
    
    # Reset color to black
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, txt=f"AI Confidence Score: {confidence}", ln=True, align='L')
    pdf.ln(10)
    
    # Add Patient Image
    with tempfile.NamedTemporaryFile(delete=False, suffix=".jpg") as tmpfile:
        patient_img.save(tmpfile.name)
        pdf.image(tmpfile.name, x=10, y=70, w=100)
    
    pdf.ln(110) # Move cursor down
    
    # Disclaimer in PDF
    pdf.set_font("Arial", 'I', 8)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(0, 5, txt="DISCLAIMER: This report is generated by an Artificial Intelligence system (LungsAI) for research/educational purposes only. It is not a substitute for professional medical advice, diagnosis, or treatment.")
    
    return pdf.output(dest="S").encode("latin-1")

# --- Validator (The Gatekeeper) ---
def is_valid_medical_image(pil_img):
    # Check 1: Saturation (Reject Colorful Images)
    img_hsv = pil_img.convert('HSV')
    s_channel = img_hsv.split()[1]
    avg_saturation = ImageStat.Stat(s_channel).mean[0]
    if avg_saturation > 30: return False
    
    # Check 2: Brightness (Reject White/Black Screens)
    img_gray = pil_img.convert('L')
    stat = ImageStat.Stat(img_gray)
    avg_brightness = stat.mean[0]
    if avg_brightness < 30 or avg_brightness > 210: return False
    
    # Check 3: Flatness (Reject Digital Screenshots)
    histogram = img_gray.histogram()
    total_pixels = img_gray.width * img_gray.height
    most_frequent_pixel_count = max(histogram)
    if (most_frequent_pixel_count / total_pixels) > 0.35: return False
    
    return True

# ---------------------------------------------------------------------
# 3. Sidebar (UPDATED EMAIL)
# ---------------------------------------------------------------------
with st.sidebar:
    st.image("https://cdn-icons-png.flaticon.com/512/3063/3063176.png", width=80)
    st.title("🫁 LungsAI")
    st.caption("Advanced Pneumonia Detection System")
    st.write("---")
    st.info("**Features:**\n- Deep Learning Analysis\n- Smart Image Validation\n- Automated PDF Reports")
    st.write("---")
    
    # --- EMAIL UPDATE HERE ---
    st.write("### 📞 Contact Developer")
    st.write("**Name:** Shahed Rahman")
    st.write("**Email:** shahedrahmanltd@gmail.com")
    
    st.write("---")
    st.warning("⚠️ **Note:** For research purpose only.")

# ---------------------------------------------------------------------
# 4. Main App Logic
# ---------------------------------------------------------------------
st.markdown("<h1 style='text-align: center;'>🫁 LungsAI – Deep Learning Pneumonia Classifier</h1>", unsafe_allow_html=True)
st.divider()

@st.cache_resource
def load_ai_model():
    model = load_model('pneumonia_model.h5')
    return model

try:
    model = load_ai_model()
except:
    st.error("🚨 Critical Error: Model file not found!")

st.write("### 📤 Upload Patient X-Ray")
uploaded_file = st.file_uploader("Upload Chest X-Ray (JPEG/PNG)", type=["jpg", "png", "jpeg"])

if uploaded_file is not None:
    img = Image.open(uploaded_file)
    
    # --- VALIDATION ---
    if is_valid_medical_image(img):
        img = img.convert('RGB')
        col1, col2, col3 = st.columns([1, 2, 1])
        with col2:
            st.image(img, caption='Patient X-Ray', use_container_width=True)
            left, mid, right = st.columns([0.5, 2, 0.5])
            with mid:
                analyze_button = st.button('🔍 RUN DIAGNOSIS')

        if analyze_button:
            with st.spinner('🧬 AI is analyzing lung patterns...'):
                # 1. Preprocessing
                img_resized = img.resize((150, 150))
                img_array = image.img_to_array(img_resized)
                img_batch = np.expand_dims(img_array, axis=0)
                img_norm = img_batch / 255.0

                # 2. Prediction
                prediction = model.predict(img_norm)
                score = prediction[0][0]
                
                # 3. Process Result
                is_pneumonia = score > 0.5
                conf_val = score if is_pneumonia else 1 - score
                conf_str = f"{conf_val*100:.2f}%"
                result_text = "PNEUMONIA DETECTED" if is_pneumonia else "NORMAL"

                # 4. Display Results
                st.write("---")
                st.subheader("📋 Diagnosis Report")
                res_col1, res_col2 = st.columns(2)
                
                if is_pneumonia:
                    with res_col1:
                        st.error("⚠️ **DETECTION: POSITIVE**")
                        st.write("Signs of **Pneumonia** detected.")
                    with res_col2:
                        st.metric("Confidence", conf_str, "High Risk", delta_color="inverse")
                else:
                    with res_col1:
                        st.success("✅ **DETECTION: NEGATIVE**")
                        st.write("Lungs appear **Normal**.")
                    with res_col2:
                        st.metric("Confidence", conf_str, "Low Risk")

                # 5. Generate PDF Report
                pdf_bytes = create_pdf(img, result_text, conf_str, is_pneumonia)
                
                st.write("---")
                st.download_button(
                    label="📄 Download Full Medical Report (PDF)",
                    data=pdf_bytes,
                    file_name="LungsAI_Report.pdf",
                    mime="application/pdf",
                )

    else:
        st.toast('⚠️ Invalid Image!', icon='🚫')
        st.error("⛔ Invalid Image Detected: Upload a valid Chest X-Ray.")

# ---------------------------------------------------------------------
# 5. Terms & Footer (UPDATED TEXT)
# ---------------------------------------------------------------------
st.write(""); st.write("")

# আপনার দেওয়া টেক্সট হুবহু এখানে বসানো হয়েছে
with st.expander("⚖️ Terms of Service & Medical Disclaimer (Read Carefully)"):
    st.markdown("""
    ### 1. Intended Use
    This application (**LungsAI**) is a prototype designed for **educational and research purposes only** (Science Fair Project 2025). It is NOT a certified medical device.

    ### 2. No Medical Advice
    The results provided by this AI system should **never** be treated as a final medical diagnosis.
    * Always consult a certified doctor or radiologist for official diagnosis.
    * Do not ignore professional medical advice based on this app's results.

    ### 3. Accuracy & Liability
    While the model has a high accuracy rate (~95%), errors (False Positives/Negatives) can occur. The developer (**Shahed Rahman**) is not liable for any decisions made based on this software.

    ### 4. Data Privacy
    This application processes images temporarily for analysis. No patient data or images are permanently stored on the server.
    """)

st.markdown("""
    <div style='text-align: center; margin-top: 50px; color: #888; font-size: 12px;'>
        <hr>
        <p>Developed by <b>Shahed Rahman</b> | Diploma in Engineering Student</p>
        <p>© 2026 LungsAI Research Project. All rights reserved.</p>
    </div>
    """, unsafe_allow_html=True)